version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/vul-scans"
      - "/tag"
      - "/apko-snapshot"
      - "/scan-apk"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    groups:
      patch-updates:
        update-types:
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/tag"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    groups:
      patch-updates:
        update-types:
          - "patch"
