# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Scan image snapshot'
description: |
  This action scans an OCI image

inputs:

  image:
    description: |
      The container image into which we should publish attestation.
    required: true

  registry:
    description: |
      Which registry to use.
    default: ghcr.io
    required: false

  username:
    description: |
      The username to use for docker login step.
    default: ${{ github.repository_owner }}
    required: false

  password:
    description: |
      The token to use for docker login step.
    required: false
    default: ${{ github.token }}

  debug:
    description: |
      Enable debug logging.
    required: false
    default: "false"

  UPLOAD_GITHUB_CODE:
    description: |
      Upload Scan results to github security
    required: false
    default: "false"

  RUN_TRIVY:
    description: Run trivy scan or not.
    required: true
    default: "true"

  RUN_GRYPE:
    description: Run grype scan or not.
    required: true
    default: "true"

  RUN_SNYK:
    description: Run snyk scan or not, set SNYK_TOKEN as well
    required: true
    default: "true"

  SNYK_TOKEN:
    description: |
      SNYK Token for vul scanning
    required: true

  SNYK_VERSION:
    description: |
      SNYK Token for vul scanning
    required: false
    default: "v1.966.0"

outputs:
  TRIVY_COUNT:
    description: Number of vulnerables in trivy scan
    value: ${{ steps.scan-report.outputs.TRIVY_COUNT }}
  GRYPE_COUNT:
    description: Number of vulnerables in Grype scan
    value: ${{ steps.scan-report.outputs.GRYPE_COUNT }}
  SNYK_COUNT:
    description: Number of Vulnerables in Snyk scan
    value: ${{ steps.scan-report.outputs.SNYK_COUNT }}

runs:
  using: composite
  steps:
    - name: Setup cosign
      uses: sigstore/cosign-installer@48866aa521d8bf870604709cd43ec2f602d03ff2 #v2.4.1
      with:
        cosign-release: v1.9.0

    - uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b # v1.13.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - id: scan-start
      run: |
        echo ::set-output name=date::$(TZ=Zulu date "+%Y-%m-%dT%H:%M:%SZ")
      shell: bash

    - id: install-snyk
      if: inputs.RUN_SNYK == 'true'
      name: Run Snyk to check Docker image for vulnerabilities
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
        SNYK_VERSION: ${{ inputs.SNYK_VERSION }}
      run: |
        set -ex

        SNYK_DOWNLOAD="snyk-linux"

        if [ "$RUNNER_OS" == "Linux" ]; then
          SNYK_DOWNLOAD="snyk-linux"
        elif [ "$RUNNER_OS" == "Windows" ]; then
          SNYK_DOWNLOAD="snyk-win.exe"
        elif [ "$RUNNER_OS" == "macOS" ]; then
          SNYK_DOWNLOAD="snyk-macos"
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi

        curl -s -o snyk https://static.snyk.io/cli/${SNYK_VERSION}/${SNYK_DOWNLOAD}

        echo "SNYK_VERSION=${SNYK_VERSION}" >> $GITHUB_ENV
        echo "SNYK_URL=https://static.snyk.io/cli/${SNYK_VERSION}/${SNYK_DOWNLOAD}" >> $GITHUB_ENV

        chmod +x snyk

    - name: Run Snyk to check Docker image for vulnerabilities
      if: inputs.RUN_SNYK == 'true'
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.SNYK_TOKEN }}
      run: |
        ./snyk container test ${{ inputs.image }} \
        --app-vulns --json --severity-threshold=low \
        --json-file-output=snyk.json >/dev/null || true

    - name: Cosign Attest Snyk results
      if: inputs.RUN_SNYK == 'true'
      shell: bash
      id: snyk-attest
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        ATTESTATION=$(mktemp)

        echo "Snyk SCANNER_URI: ${{ env.SNYK_URL }}"
        echo "Snyk SCANNER_VERSION: ${{ env.SNYK_VERSION }}"

        cat > "${ATTESTATION}" <<EOF
        {
            "invocation": {
              "parameters": null,
              "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "event_id": "${{ github.run_id }}",
              "builder.id": "${{ github.workflow }}"
            },
            "scanner": {
              "uri": "${{ env.SNYK_URL }}",
              "version": "${{ env.SNYK_VERSION }}",
              "result": $(cat snyk.json | jq .)
            },
            "metadata": {
              "scanStartedOn": "${{ steps.scan-start.outputs.date }}",
              "scanFinishedOn": "$(TZ=Zulu date "+%Y-%m-%dT%H:%M:%SZ")"
            }
        }
        EOF

        export COSIGN_EXPERIMENTAL="$COSIGN_EXPERIMENTAL"

        cosign attest --type vuln --predicate "${ATTESTATION}" ${{ inputs.image }}


    - name:  Scan image with AquaSec/Trivy
      if: inputs.RUN_TRIVY == 'true'
      uses: aquasecurity/trivy-action@0105373003c89c494a3f436bd5efc57f3ac1ca20 #v0.5.1
      id: trivy-scan
      with:
        image-ref: ${{ inputs.image }}
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: 0
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'

    - name: Cosign Attest trivy results
      if: inputs.RUN_TRIVY == 'true'
      shell: bash
      id: trivy-attest
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        ATTESTATION=$(mktemp)

        export SCANNER_URI=$(cat trivy-results.sarif | jq -r .runs[0].tool.driver.informationUri)
        export SCANNER_VERSION=$(cat trivy-results.sarif | jq -r .runs[0].tool.driver.version)

        echo "trivy SCANNER_URI: $SCANNER_URI"
        echo "trivy SCANNER_VERSION: $SCANNER_VERSION"

        cat > "${ATTESTATION}" <<EOF
        {
            "invocation": {
              "parameters": null,
              "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "event_id": "${{ github.run_id }}",
              "builder.id": "${{ github.workflow }}"
            },
            "scanner": {
              "uri": "$SCANNER_URI",
              "version": "$SCANNER_VERSION",
              "result": $(cat trivy-results.sarif | jq .)
            },
            "metadata": {
              "scanStartedOn": "${{ steps.scan-start.outputs.date }}",
              "scanFinishedOn": "$(TZ=Zulu date "+%Y-%m-%dT%H:%M:%SZ")"
            }
        }
        EOF

        export COSIGN_EXPERIMENTAL="$COSIGN_EXPERIMENTAL"

        cosign attest --type vuln --predicate "${ATTESTATION}" ${{ inputs.image }}


    - name: Scan image with Anchore/Grype
      if: inputs.RUN_GRYPE == 'true'
      id: grype-scan
      uses: anchore/scan-action@ecfd0e98932e57ea8f68f29c4f418fc41a8194db
      with:
        image: ${{ inputs.image }}
        fail-build: false
        severity-cutoff: low

    - name: Cosign Attest Grype results
      if: inputs.RUN_GRYPE == 'true'
      shell: bash
      id: grype-attest
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        ATTESTATION=$(mktemp)

        export SCANNER_URI=$(cat ${{ steps.grype-scan.outputs.sarif }} | jq -r .runs[0].tool.driver.informationUri)
        export SCANNER_VERSION=$(cat ${{ steps.grype-scan.outputs.sarif }} | jq -r .runs[0].tool.driver.version)

        echo "grype SCANNER_URI: $SCANNER_URI"
        echo "grype SCANNER_VERSION: $SCANNER_VERSION"

        cat > "${ATTESTATION}" <<EOF
        {
            "invocation": {
              "parameters": null,
              "uri": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
              "event_id": "${{ github.run_id }}",
              "builder.id": "${{ github.workflow }}"
            },
            "scanner": {
              "uri": "$SCANNER_URI",
              "version": "$SCANNER_VERSION",
              "result": $(cat ${{ steps.grype-scan.outputs.sarif }} | jq .)
            },
            "metadata": {
              "scanStartedOn": "${{ steps.scan-start.outputs.date }}",
              "scanFinishedOn": "$(TZ=Zulu date "+%Y-%m-%dT%H:%M:%SZ")"
            }
        }
        EOF

        export COSIGN_EXPERIMENTAL="$COSIGN_EXPERIMENTAL"

        cosign attest --type vuln --predicate "${ATTESTATION}" ${{ inputs.image }}


    - name: High Level Scan report
      id: scan-report
      shell: bash
      run: |
        GRYPE_COUNT="n/a"
        if [ "${{ inputs.RUN_GRYPE }}" = "true" ]; then
          GRYPE_COUNT=$(cat ${{ steps.grype-scan.outputs.sarif }} | jq '.runs[0].results | length')
        fi

        TRIVY_COUNT="n/a"
        if [ "${{ inputs.RUN_TRIVY }}" = "true" ]; then
          TRIVY_COUNT=$(cat trivy-results.sarif | jq '.runs[0].results | length')
        fi

        SNYK_COUNT="n/a"
        if [ "${{ inputs.RUN_SNYK }}" = "true" ]; then
          SNYK_COUNT=$(cat snyk.json | jq .uniqueCount)
        fi

        echo "SNYK_COUNT: $SNYK_COUNT, GRYPE_COUNT: $GRYPE_COUNT, TRIVY_COUNT: $TRIVY_COUNT"

        echo "::set-output name=SNYK_COUNT::$SNYK_COUNT"
        echo "::set-output name=GRYPE_COUNT::$GRYPE_COUNT"
        echo "::set-output name=TRIVY_COUNT::$TRIVY_COUNT"
