# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Build image snapshot with apko'
description: |
  This action builds an OCI image with apko, given a config file
  and base tag to use.

inputs:
  config:
    description: |
      The config file to use for building the image.
    default: .apko.yaml

  base-tag:
    description: |
      The base tag to use for publishing the image.
    default: ghcr.io/${{ github.repository }}
    required: true

  username:
    description: |
      The username to use for docker login step.
    default: ${{ github.repository_owner }}

  token:
    description: |
      The token to use for docker login step.
    default: ${{ github.token }}

outputs:
  digest:
    value: ${{ steps.apko.outputs.digest }}
    description: |
      The digest of the published container image.

runs:
  using: composite
  steps:
    - name: Setup cosign
      uses: sigstore/cosign-installer@main
      with:
        cosign-release: v1.5.2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Generate snapshot date
      id: snapshot-date
      run: |
        echo ::set-output name=date::$(date -u +%Y%m%d)
      shell: bash

    - uses: chainguard-dev/actions/apko-build@main
      id: apko
      with:
        config: ${{ inputs.config }}
        tag: ${{ inputs.base-tag }}:${{ steps.snapshot-date.outputs.date }} ${{ inputs.base-tag }}:latest

    - uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b # v1.13.0
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - shell: bash
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign ${{ steps.apko.outputs.digest }} \
            -a sha=${{ github.sha }} \
            -a run_id=${{ github.run_id }} \
            -a run_attempt=${{ github.run_attempt }}

