# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Build image snapshot with apko'
description: |
  This action builds an OCI image with apko, given a config file
  and base tag to use.

inputs:
  config:
    description: |
      The config file to use for building the image.
    required: true
    default: .apko.yaml

  base-tag:
    description: |
      The container repository into which we should publish images.
    default: ghcr.io/${{ github.repository }}
    required: true

  target-tag:
    description: |
      The tag this build will produce upon success.  It will also be used
      to form a date-based variant for tracking over time.
    default: latest
    required: true

  registry:
    description: |
      Which registry to use.
    default: ghcr.io
    required: true

  username:
    description: |
      The username to use for docker login step.
    required: true
    default: ${{ github.repository_owner }}

  token:
    description: |
      The token to use for docker login step.
    required: true
    default: ${{ github.token }}

  use-docker-mediatypes:
    description: |
      Use Docker mediatypes for building the image.
    required: false

  keyring-append:
    description: |
      The value to pass to --keyring-append.
    required: false
    default: ''

  archs:
    description: |
      The architectures to build for.
    required: false
    default: ''

  additional-tags:
    description: |
      Additional tags for the final image.
    required: false
    default: ''

  package-version-tag:
    description: |
      apko can tag the final image with the version of the corresponding apk package passed in here.
    required: false
    default: ''

  tag-suffix:
    description: |
      Suffix to use with the package-version-tag feature, if any.
    required: false
    default: ''

  debug:
    description: |
      Enable debug logging.
    required: false
    default: 'false'

  image_refs:
    description: |
      The value to pass to --image-refs.
    default: apko.images

  automount-src:
    description: |
      In subsequent steps, if this directory is found, create a copy at automount-dest (inside container)
    default: ${{ github.workspace }}/.apko-automount

  automount-dest:
    description: |
      In subsequent steps, if automount-src is found, create a copy at this location (inside container)
    default: /work

  FULCIO_URL:
    required: false
    description: address of sigstore PKI server (default "https://fulcio.sigstore.dev")
    default: "https://fulcio.sigstore.dev"

  REKOR_URL:
    required: false
    description: address of rekor STL server (default "https://rekor.sigstore.dev")
    default: "https://rekor.sigstore.dev"

outputs:
  digest:
    value: ${{ steps.apko.outputs.digest }}
    description: |
      The digest of the published container image.

runs:
  using: composite
  steps:
    - name: Setup cosign
      uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 # v2.6.0
      with:
        cosign-release: v1.11.1

    - uses: imjasonh/setup-crane@v0.2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # v2.0.0

    - name: Generate snapshot date
      id: snapshot-date
      run: |
        echo ::set-output name=date::$(date -u +%Y%m%d)
        echo ::set-output name=epoch::$(date -u +%s)
      shell: bash

    # Only publish the versioned tag to start.  After we have signed and
    # attested things, then we use crane to update :latest below.
    - uses: distroless/actions/apko-publish@main
      id: apko
      with:
        config: ${{ inputs.config }}
        tag: ${{ inputs.base-tag }}:${{ inputs.target-tag }}-${{ steps.snapshot-date.outputs.date }}
        image_refs: ${{ inputs.image_refs }}
        source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}
        use-docker-mediatypes: ${{ inputs.use-docker-mediatypes }}
        keyring-append: ${{ inputs.keyring-append }}
        archs: ${{ inputs.archs }}
        debug: ${{ inputs.debug }}
        automount-src: ${{ inputs.automount-src }}
        automount-dest: ${{ inputs.automount-dest }}
        package-version-tag: ${{ inputs.package-version-tag }}
        tag-suffix: ${{ inputs.tag-suffix }}

    - uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b # v1.13.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - shell: bash
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign $(cat ${{ inputs.image_refs }}) \
            --fulcio-url ${{ inputs.FULCIO_URL }}  --rekor-url ${{ inputs.REKOR_URL }} \
            -a sha=${{ github.sha }} \
            -a run_id=${{ github.run_id }} \
            -a run_attempt=${{ github.run_attempt }}

    # Now that everything else has completed successfully, update the target tag.
    # based on the digest produced above.
    - shell: bash
      run: |
        crane cp ${{ steps.apko.outputs.digest }} ${{ inputs.base-tag }}:${{ inputs.target-tag }}

        for tag in $(echo ${{ inputs.additional-tags }} | sed "s/,/ /g")
        do
          crane cp ${{ steps.apko.outputs.digest }} ${{ inputs.base-tag }}:$tag
        done
