# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Add additonal tags to image'
description: |
  This action discovers additional tags for the distroless image
  and adds them to the image.

inputs:
  distroless_image:
    description: |
      The distroless image to add tags to
    required: true
    default: ''

  docker_image:
    description: |
      The docker image to compare the distroless image against.
    default: ''
    required: true

  docker_image_tag:
    description: |
      Tag for the docker image.
    default: ''
    required: true

  registry:
    description: |
      Which registry to use.
    default: ghcr.io
    required: true

  username:
    description: |
      The username to use for docker login step.
    required: true
    default: ${{ github.repository_owner }}

  token:
    description: |
      The token to use for docker login step.
    required: true
    default: ${{ github.token }}

  excluded_tags:
    description: |
      Comma separated list of tag regexes to ignore.
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: chainguard-images/actions
    - uses: imjasonh/setup-crane@31b88efe9de28ae0ffa220711af4b60be9435f6e # v0.4

    - name: Set up Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version: 1.25
        check-latest: true

    - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Run tagging script
      shell: bash
      run: |
        (cd tag && go build -o ../tag-run main.go)
        ./tag-run \
          -distroless-image="${{ inputs.distroless_image }}" \
          -docker-image-tag="${{ inputs.docker_image_tag }}" \
          -docker-image="${{ inputs.docker_image }}" \
          -excluded-tags="${{ inputs.excluded_tags }}"
