# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Add additonal tags to image'
description: |
  This action discovers additional tags for the distroless image
  and adds them to the image.

inputs:
  distroless_image:
    description: |
      The distroless image to add tags to
    required: true
    default: ''

  docker_image:
    description: |
      The docker image to compare the distroless image against.
    default: ''
    required: true

  docker_image_tag:
    description: |
      Tag for the docker image.
    default: ''
    required: true

  registry:
    description: |
      Which registry to use.
    default: ghcr.io
    required: true

  username:
    description: |
      The username to use for docker login step.
    required: true
    default: ${{ github.repository_owner }}

  token:
    description: |
      The token to use for docker login step.
    required: true
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      with:
        repository: ${{ github.repository_owner }}/actions
    - uses: imjasonh/setup-crane@v0.1
    - name: Set up Go
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # v3.3.0
      with:
        go-version: 1.18

    - uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b # v1.13.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Run tagging script
      shell: bash
      run: |
        cd tag
        go build -o tag main.go
        ./tag -distroless-image="${{ inputs.distroless_image }}" -docker-image-tag="${{ inputs.docker_image_tag }}" -docker-image="${{ inputs.docker_image }}"
