# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Add additonal tags to image'
description: |
  This action discovers additional tags for the distroless image
  and adds them to the image.

inputs:
  distroless_image:
    description: |
      The distroless image to add tags to
    required: true
    default: ''

  docker_image:
    description: |
      The docker image to compare the distroless image against.
    default: ''
    required: true

  docker_image_tag:
    description: |
      Tag for the docker image.
    default: ''
    required: true

  registry:
    description: |
      Which registry to use.
    default: ghcr.io
    required: true

  username:
    description: |
      The username to use for docker login step.
    required: true
    default: ${{ github.repository_owner }}

  token:
    description: |
      The token to use for docker login step.
    required: true
    default: ${{ github.token }}

  excluded_tags:
    description: |
      Comma separated list of tag regexes to ignore.
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: chainguard-images/actions
    - uses: imjasonh/setup-crane@v0.1
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: 1.19
        check-latest: true

    - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Run tagging script
      shell: bash
      run: |
        (cd tag && go build -o ../tag-run main.go)
        ./tag-run \
          -distroless-image="${{ inputs.distroless_image }}" \
          -docker-image-tag="${{ inputs.docker_image_tag }}" \
          -docker-image="${{ inputs.docker_image }}" \
          -excluded-tags="${{ inputs.excluded_tags }}"
