# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Add additonal tags to image'
description: |
  This action discovers additional tags for the distroless image
  and adds them to the image.

inputs:
  distroless_image:
    description: |
      The distroless image to add tags to
    required: true
    default: ''

  docker_image:
    description: |
      The docker image to compare the distroless image against.
    default: ''
    required: true

  docker_image_tag:
    description: |
      Tag for the docker image.
    default: ''
    required: true

  registry:
    description: |
      Which registry to use.
    default: ghcr.io
    required: true

  username:
    description: |
      The username to use for docker login step.
    required: true
    default: ${{ github.repository_owner }}

  token:
    description: |
      The token to use for docker login step.
    required: true
    default: ${{ github.token }}

  excluded_tags:
    description: |
      Comma separated list of tag regexes to ignore.
    default: ''
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        repository: chainguard-images/actions
    - uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987 # v0.5

    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version: 1.25
        check-latest: true

    - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Run tagging script
      shell: bash
      run: |
        (cd tag && go build -o ../tag-run main.go)
        ./tag-run \
          -distroless-image="${{ inputs.distroless_image }}" \
          -docker-image-tag="${{ inputs.docker_image_tag }}" \
          -docker-image="${{ inputs.docker_image }}" \
          -excluded-tags="${{ inputs.excluded_tags }}"
