# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Scan APK for vulnerabilities'
description: |
  This action scans an APK for vulnerabilities by turning it into an OCI image first.

inputs:

  repositories:
    description: |
      A comma-delimited list of APK repositories to include.
    required: false
    default: https://packages.wolfi.dev/os

  keyring:
    description: |
      A comma-delimited list of APK keyrings to include.
    required: false
    default: https://packages.wolfi.dev/os/wolfi-signing.rsa.pub

  package:
    description: |
      The APK to scan for vulnerabilities.
    required: true

  architecture:
    description: |
      The architecture to scan the package for vulnerabilities.
    required: false
    default: "x86_64"

outputs:
  vuln-count:
    description: Number of vulnerables in Grype scan
    value: ${{ steps.scan-report.outputs.vuln-count }}

runs:
  using: composite
  steps:
    - uses: chainguard-dev/actions/setup-registry@3e8a2a226fad9e1ecbf2d359b8a7697554a4ac6d # v1.5.10
      with:
        port: 1234

    - shell: bash
      id: mkconfig
      run: |
        TMP="$GITHUB_WORKSPACE/config_file"

        cat > "${TMP}" <<EOF
        contents:
          repositories: $(echo "${{ inputs.repositories }}" | tr -d '[:space:]' | jq --raw-input -c --slurp 'split(",")')
          keyring: $(echo "${{ inputs.keyring }}" | tr -d '[:space:]' | jq --raw-input -c --slurp 'split(",")')
          packages:
          - ${{ inputs.package }}

        archs:
        - ${{ inputs.architecture }}
        EOF

        echo "CONFIG_FILE=${TMP}" >> $GITHUB_ENV

    - shell: bash
      run: |
        cat ${{ env.CONFIG_FILE }}

    - uses: ./apko-publish
      with:
        config: ${{ env.CONFIG_FILE }}
        tag: localhost:1234/apk-scan

    - id: grype-scan
      uses: anchore/scan-action@40a61b52209e9d50e87917c5b901783d546b12d0 # v7.2.1
      with:
        image: localhost:1234/apk-scan
        fail-build: false
        severity-cutoff: low

    - id: scan-report
      shell: bash
      run: |
        echo "vuln-count=$(cat ${{ steps.grype-scan.outputs.sarif }} | jq '.runs[0].results | length')" >> $GITHUB_OUTPUT
